### PR TITLE
Update existing refs to the current version of the book

### PR DESCRIPTION
**Pull request by s-heppner**
Wherever possible, we referenced DotAAS Part 1a.
When necessary, we added an inline comment when referencing DotAAS Part 3a

### CODE REVIEW

**Comment by mristin** [comment]
@mristin note to myself: we should write references as URLs next week (Feb 20-26).

**Comment by mristin** [comment]
@s-heppner @zrgt could you please post a couple of example URLs to the book chapters (both Part 1a and 3a)?

**Comment by s-heppner** [comment]
I don't think this is possible to do yet, as the spec is not published. So we are not able to know how the final URLs will look like.

**Comment by mristin** [comment]
> I don't think this is possible to do yet, as the spec is not published. So we are not able to know how the final URLs will look like.

I think URLs to Coyo would already do the trick. As long as we can adapt them with "Replace all", it should be OK. Or the structure of Part 1a and 3a is still not final (*e.g.* classes moving from one book to the other)?

**Comment by s-heppner** [comment]
I don't think (and hope) that classes would still move. Nevertheless, Coyo is deprecated (it's not a plain IDTA workstream, not the joined Working Group with Plattform Industrie 4.0) and IDTA use a Teams channel to share data. On this channel, I couldn't find the newest version of the spec, though.

**Pull request merged**
